"""Core data types for the Polymarket trading bot."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    LIMIT = "LIMIT"
    MARKET = "MARKET"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    OPEN = "OPEN"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class SignalType(str, Enum):
    MISPRICING = "MISPRICING"
    ARBITRAGE = "ARBITRAGE"
    HEDGED_ARB = "HEDGED_ARB"


class CopyTradeResponse(str, Enum):
    FLAG_ONLY = "flag_only"
    REDUCE_SIZE = "reduce_size"
    RANDOMIZE_TIMING = "randomize_timing"


@dataclass
class Market:
    """Represents a Polymarket prediction market."""

    condition_id: str
    question: str
    tokens: list[Token]
    category: str = ""
    end_date: datetime | None = None
    active: bool = True
    liquidity_usd: float = 0.0
    volume_usd: float = 0.0
    description: str = ""
    slug: str = ""

    @property
    def is_binary(self) -> bool:
        return len(self.tokens) == 2


@dataclass
class Token:
    """A single outcome token in a market."""

    token_id: str
    outcome: str
    price: float = 0.0
    book_depth_usd: float = 0.0


@dataclass
class OrderBook:
    """Order book snapshot for a token."""

    token_id: str
    bids: list[PriceLevel]
    asks: list[PriceLevel]
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def best_bid(self) -> float:
        return self.bids[0].price if self.bids else 0.0

    @property
    def best_ask(self) -> float:
        return self.asks[0].price if self.asks else 1.0

    @property
    def mid_price(self) -> float:
        return (self.best_bid + self.best_ask) / 2.0

    @property
    def spread(self) -> float:
        return self.best_ask - self.best_bid


@dataclass
class PriceLevel:
    """A single price level in an order book."""

    price: float
    size: float


@dataclass
class Signal:
    """A trading signal generated by the signal engine."""

    signal_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    signal_type: SignalType = SignalType.MISPRICING
    market: Market | None = None
    token: Token | None = None
    side: Side = Side.BUY
    model_probability: float = 0.0
    market_price: float = 0.0
    expected_value: float = 0.0
    confidence: float = 0.0
    liquidity_usd: float = 0.0
    recommended_size_usd: float = 0.0
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def ev_after_fees(self) -> float:
        fee_rate = 0.02  # Polymarket ~2% fee
        return self.expected_value - (self.recommended_size_usd * fee_rate)


@dataclass
class Order:
    """Represents a trading order."""

    order_id: str = field(default_factory=lambda: str(uuid.uuid4())[:12])
    signal_id: str = ""
    token_id: str = ""
    market_condition_id: str = ""
    side: Side = Side.BUY
    order_type: OrderType = OrderType.LIMIT
    price: float = 0.0
    size: float = 0.0
    size_usd: float = 0.0
    status: OrderStatus = OrderStatus.PENDING
    filled_size: float = 0.0
    filled_price: float = 0.0
    slippage: float = 0.0
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    exchange_order_id: str = ""
    is_paper: bool = True
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def fill_ratio(self) -> float:
        return self.filled_size / self.size if self.size > 0 else 0.0


@dataclass
class Position:
    """An open position in a market."""

    position_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    token_id: str = ""
    market_condition_id: str = ""
    side: Side = Side.BUY
    size: float = 0.0
    entry_price: float = 0.0
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    opened_at: datetime = field(default_factory=datetime.utcnow)
    is_paper: bool = True

    @property
    def exposure_usd(self) -> float:
        return self.size * self.current_price

    @property
    def cost_basis(self) -> float:
        return self.size * self.entry_price

    def update_pnl(self, current_price: float) -> None:
        self.current_price = current_price
        if self.side == Side.BUY:
            self.unrealized_pnl = self.size * (current_price - self.entry_price)
        else:
            self.unrealized_pnl = self.size * (self.entry_price - current_price)


@dataclass
class TradeLog:
    """Audit log entry for a trade decision."""

    timestamp: datetime = field(default_factory=datetime.utcnow)
    signal: Signal | None = None
    order: Order | None = None
    risk_checks: dict[str, bool] = field(default_factory=dict)
    risk_adjustments: dict[str, Any] = field(default_factory=dict)
    decision: str = ""
    reason: str = ""


@dataclass
class WalletActivity:
    """On-chain wallet activity record."""

    wallet_address: str = ""
    tx_hash: str = ""
    market_condition_id: str = ""
    token_id: str = ""
    side: Side = Side.BUY
    size: float = 0.0
    price: float = 0.0
    timestamp: datetime = field(default_factory=datetime.utcnow)
    block_number: int = 0


@dataclass
class CopyTradeAlert:
    """Alert when potential copy trading is detected."""

    suspect_wallet: str = ""
    our_order: Order | None = None
    suspect_activity: WalletActivity | None = None
    similarity_score: float = 0.0
    time_delta_seconds: float = 0.0
    recommended_action: CopyTradeResponse = CopyTradeResponse.FLAG_ONLY
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class BacktestResult:
    """Results from a backtest run."""

    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    total_pnl: float = 0.0
    max_drawdown: float = 0.0
    sharpe_ratio: float = 0.0
    win_rate: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    realized_vs_expected_pnl: float = 0.0
    peak_exposure: float = 0.0
    trades: list[TradeLog] = field(default_factory=list)
    equity_curve: list[float] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
